# Name of the GitHub Actions workflow.
name: Deploy to GitHub Pages

# Controls when the action will run. 
# This is configured to run on every push to the 'main' branch.
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build-and-deploy:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # These permissions are required to allow the action to create the gh-pages branch
    # and push the built application to it. This is the main fix for the "403 Forbidden" error.
    permissions:
      contents: write

    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Sets up a Java environment for the Gradle build.
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Runs the Gradle command to build the WebAssembly distribution for the browser.
      # Ensure this command successfully creates the 'productionExecutable' directory.
      - name: Build with Gradle
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      # Step 4: Deploys the built application to the 'gh-pages' branch.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # The GITHUB_TOKEN is a special access token that GitHub automatically creates.
          # It's used to authenticate in a workflow run.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # This is the directory that contains the files to be deployed.
          # It must match the output directory of the 'Build with Gradle' step.
          publish_dir: ./composeApp/build/dist/wasmJs/productionExecutable

